version: "3.9"

services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: ramanadb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: artgallery-backend:latest
    container_name: springboot-app
    ports:
      - "2004:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ramanadb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: docker
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-mysql-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/user/login"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: artgallery-frontend:latest
    container_name: frontend-app
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:2004
    depends_on:
      - backend
    restart: on-failure
    networks:
      - springboot-mysql-net

volumes:
  mysql_data:

networks:
  springboot-mysql-net:
    driver: bridge
